### ISSUE TITLE
ShapeMaster crash

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#68]
Left a patch running, returned to the PC to the crash dialog though the patch was still playing.

[845.834 fatal src/main.cpp:45] Fatal signal 6. Stack trace:
13: ./Rack(+0x1f63b5) [0x558ee88ed3b5]
12: /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7fc6600ec040]
11: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7fc6600ebfb7]
10: /lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7fc6600ed921]
9: /lib/x86_64-linux-gnu/libc.so.6(+0x89967) [0x7fc660136967]
8: /lib/x86_64-linux-gnu/libc.so.6(+0x909da) [0x7fc66013d9da]
7: /lib/x86_64-linux-gnu/libc.so.6(cfree+0x54c) [0x7fc660144f7c]
6: ./Rack(_ZNSt6vectorIPN4rack7history6ActionESaIS3_EE17_M_realloc_insertIJRKS3_EEEvN9__gnu_cxx17__normal_iteratorIPS3_S5_EEDpOT_+0xca) [0x558ee88bbd9e]
5: ./Rack(_ZN4rack7history5State4pushEPNS0_6ActionE+0xe8) [0x558ee88bbb50]
4: /home/ewen/.Rack/plugins-v1/MindMeld-ShapeMasterPro/plugin.so(_ZN5Shape14randomizeShapeEP14RandomSettingsha+0x915) [0x7fc631df2213]
3: /home/ewen/.Rack/plugins-v1/MindMeld-ShapeMasterPro/plugin.so(_ZN21PresetAndShapeManager11file_workerEv+0x2d1) [0x7fc631e214a7]
2: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd6df) [0x7fc660b116df]
1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fc6626b86db]
0: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fc6601ce71f]

Also, after a while, randomising via the SM-CV expander stops working, though randomisation can still be achieved via the random menu.

**Comment by MarcBoule** [comment]
Could you share the patch please (or a small example that crashes) so that we can try to reproduce this?
Just to understand, Rack did not crash and kept playing (but the SM-CV expander no longer worked), since the log seems to show a real crash. Very weird!

**Comment by MarcBoule** [comment]
After a bit of searching, the only thing I can see is that the crash may have been caused by a bug in ShapeMaster where invert, reverse and random via the SM-CV expander were causing undo actions to be added to Rack undo history upon every trigger. That should not be the case since only the actual buttons on the module should cause undo actions to be added to the undo history. The bug was perhaps overloading the undo queue. This was fixed in the sources free and PRO, and will be part of the next updates, but if you have more info to supply (patch, etc), please let me know.

**Comment by ContemporaryInsanity** [comment]
It was a 'real' crash, the crash dialog was up, though the patch was still playing, VCV was unresponsive GUI wise and closed when I dismissed the crash dialog.

When the SM-CV randomisation stops working, re-initialising the module doesn't fix it, have to exit & restart VCV.

When I saw randomization mentioned in the stack trace I figured the crash might be related to the SM-CV issue.

Easiest way to see if it's fixed, point me at a linux build to download and I'll run my patch with that & let you know.

**Comment by ContemporaryInsanity** [comment]
Further, it is still crashing after an indeterminate amount of time with a similar stack trace:

[109.075 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
9: ./Rack(+0x1f63b5) [0x5652d36313b5]
8: /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7fdc58062040]
7: /lib/x86_64-linux-gnu/libc.so.6(+0x18ed9e) [0x7fdc581b1d9e]
6: ./Rack(_ZNSt6vectorIPN4rack7history6ActionESaIS3_EE17_M_realloc_insertIJRKS3_EEEvN9__gnu_cxx17__normal_iteratorIPS3_S5_EEDpOT_+0x90) [0x5652d35ffd64]
5: ./Rack(_ZN4rack7history5State4pushEPNS0_6ActionE+0xe8) [0x5652d35ffb50]
4: /home/ewen/.Rack/plugins-v1/MindMeld-ShapeMasterPro/plugin.so(_ZN5Shape14randomizeShapeEP14RandomSettingsha+0x915) [0x7fdc29d5a213]
3: /home/ewen/.Rack/plugins-v1/MindMeld-ShapeMasterPro/plugin.so(_ZN21PresetAndShapeManager11file_workerEv+0x2d1) [0x7fdc29d894a7]
2: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd6df) [0x7fdc58a876df]
1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fdc5a62e6db]
0: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fdc5814471f]

**Comment by MarcBoule** [comment]
I fixed some more things related to the undo history which may have also had a role in the crash, and I'll send you a link via email for a new version to try. Thanks!

**Comment by ContemporaryInsanity** [comment]
Three+ hours later, all is well.

Thanks Marc!

**Comment by MarcBoule** [comment]
Great to hear this, cheers! :-)
